### ISSUE TITLE
Getting an ES2015-related syntax error when running npm test

### ISSUE THREAD

**Issue by jonfriskics** [codeschool-projects/CodeBreakerProject#6]
CodeBreaker :
Error: Uncaught [SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode]
    at reportException (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at /Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:88:11)
    at Object.check (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:91:23)
    at Object.check (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:91:23)
    at /Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:107:12
    at wrappedEnqueued (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request._callback (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Gunzip.<anonymous> (/Users/jonfriskics/Desktop/CodeBreakerProject/node_modules/jsdom/node_modules/request/request.js:1001:12)
    at Gunzip.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Gunzip.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17) [SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode]
    setHiddenFields()

**Comment by EricJFisher** [comment]
@jonfriskics I've been unable to recreate this. (either I'm not recreating the problem properly, or it was indirectly fixed while we cleaned up the dependencies)
